import type { Metadata } from "next";
import { Analytics } from '@vercel/analytics/react';
import { SpeedInsights } from '@vercel/speed-insights/next'
import { Inter, Open_Sans, Roboto, Poppins, Lato, Merriweather, Roboto_Serif, Bitter} from "next/font/google";
import localFont from 'next/font/local';

import "./globals.css";

import Navbar from "./components/Navbar/Navbar";
import Footer from "./components/Footer/Footer";

const lato = Lato({ subsets: ["latin"], weight: ["100", "300", "400", "700", "900"] })
const bitter = Bitter({ subsets: ['latin'], weight: ['200', '300', '400', '500'] });

const helveticaNow = localFont({

  src: [
    {
      path: './HelveticaNowDisplay-Regular.woff2',
      weight: '300',
      style: 'light'
    },
    {
      path: './HelveticaNowDisplay-Medium.woff2',
      weight: '400',
      style: 'normal'
    },
    {
      path: './HelveticaNowDisplay-Bold.woff2',
      weight: '500',
      style: 'bold'
    },
    {
      path: './HelveticaNowDisplay-Black.woff2',
      weight: '600',
      style: 'bold'
    }
  ]
})

export const metadata: Metadata = {
  title: "Welcome to Proficient Engineering",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${helveticaNow.className} ${bitter.className}`}>
        <div className="layout-container">
          <Navbar />
           {children}
        </div>
        <Footer />
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  );
}
