import type { Metadata } from "next";
import { Inter, Open_Sans, Roboto, Poppins, Lato, Merriweather, Roboto_Serif, Bitter} from "next/font/google";
import "./globals.css";

const lato = Lato({ subsets: ["latin"], weight: ["100", "300", "400", "700", "900"] })
const bitter = Bitter({ subsets: ['latin'], weight: ['200', '300', '400', '500'] });

export const metadata: Metadata = {
  title: "Welcome to Proficient Engineering",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lato.className} ${bitter.className}`}>
        <div className="layout-container">
           {children}
        </div>
      </body>
    </html>
  );
}
