import type { Metadata } from "next";
import { Inter, Open_Sans, Roboto, Poppins, Lato, Merriweather, Roboto_Serif} from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const openSans = Open_Sans({ subsets: ["latin"] });
const roboto = Roboto({ weight: ["300", "400", "700", "900"], subsets: ["latin"] });
const poppinsFont = Poppins({ subsets: ["latin"], weight: ["300", "400", "600"] });
const lato = Lato({ subsets: ["latin"], weight: ["100", "300", "400", "700", "900"] })
const merriweather = Merriweather({ subsets: ["latin"], weight: ['300', '400', '700', '900']})
const robotoSerif = Roboto_Serif({ subsets: ['latin'], weight: ['300', '400', '600']});

export const metadata: Metadata = {
  title: "Welcome to Proficient Engineering",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lato.className} ${robotoSerif.className}`}>
        <div className="layout-container">
           {children}
        </div>
      </body>
    </html>
  );
}
